# Data-preprocessing parameters
subsample_N: 10000
chr_num: "22"

### Simulation parameters
min_maf: 0.005
rare_maf: 0.01
num_mrk: 5
num_mrk_neg: 0
mean_eff: 1
sd_eff: 0.01
mean_err: 0
sd_err: 0.05
num_sim: 10
